### ISSUE TITLE
Error at SimHub startup after the 1.0.3 update

### ISSUE THREAD

**Issue by mrcencig** [Romainrob/SimHub-iRacing_Pack#2]
![image](https://user-images.githubusercontent.com/6762546/102696997-b8228480-4232-11eb-824d-0e2561946429.png)

**Comment by Romainrob** [comment]
Hi.
Please try updating SimHub
This update requires the latest version. 7.3.1
https://www.simhubdash.com/download-2/

**Comment by mrcencig** [comment]
The update to 7.3.1 helped to solve the issue.
