### ISSUE TITLE
simHiracing Overlays

### ISSUE THREAD

**Issue by VladimirBYaga** [Romainrob/SimHub-iRacing_Pack#3]
![Аннотация 2021-01-02 121646](https://user-images.githubusercontent.com/76776764/103454387-6ed33a00-4cf4-11eb-88ac-83e23d209576.jpg)

First of all I want to say thank you very cool job! I use it with pleasure! But I can't find this overlay. 
I would be very grateful if you would give it!

**Comment by Romainrob** [comment]
Hi,
I'm glad you enjoy it.
The input overlay is available here: 
https://github.com/Romainrob/SimHub-Input_Display/releases

**Comment by VladimirBYaga** [comment]
Thank you . But again I can not find a link to the overlay in obs. I apologize

**Comment by Romainrob** [comment]
No worries.
You can copy the OBS link from the overlay list:
![image](https://user-images.githubusercontent.com/50543913/103455419-44ca4980-4ced-11eb-8e24-71b37a355e88.png)

But note that charts are note compatible with htlm mode on the current SimHub official release. So they won't be visible on OBS.
Support for this as just been added to 7.3.3 beta : https://www.simhubdash.com/unofficial/SimHub.7.03.3b2.zip
Either use the beta or wait for it to be included in an official release.
